/**
 * @NApiVersion 2.1
 * @NScriptType Suitelet
 *
 * Multi-item ad hoc test upload: enter up to 10 SKUs or internal IDs (one
 * per line), and this builds a Walmart MP_ITEM payload containing ALL of
 * them and submits it as a SINGLE feed -- unlike wm_sl_test_upload.js,
 * which only ever submits one item per feed. Use this to exercise the
 * multi-item shape of the MP_ITEM array (Walmart's per-item validation/
 * response behavior with more than one MPItem entry), not just the
 * single-item plumbing that tool already covers.
 *
 * Same field sourcing/translation/placeholder-fill logic as
 * wm_sl_test_upload.js, duplicated here per this project's self-contained
 * script convention (see that file's header for why).
 *
 * SANDBOX ONLY -- deliberately no environment selector, same reasoning as
 * wm_sl_test_upload.js: placeholder junk (fake UPC, fake warranty URL,
 * etc.) can never accidentally reach Walmart's production catalog.
 *
 * Submitted feeds ARE recorded to customrecord_wal_feed_submission like a
 * real run (same pattern as wm_sl_test_upload.js), with
 * custrecord_wal_feed_bucket set to 'MANUAL-TEST-MULTI' (vs. that file's
 * 'MANUAL-TEST', so multi-item runs are distinguishable) and Name prefixed
 * 'TEST-MULTI-'.
 *
 * Script parameters (own script record -- script parameter IDs are unique
 * account-wide, so wm_sl_test_upload.js's can't be reused, hence the
 * wal_multi_test_ prefix):
 *   custscript_wal_multi_test_client_id        - Walmart Marketplace API Client ID (SANDBOX)
 *   custscript_wal_multi_test_client_secret    - Walmart Marketplace API Client Secret (Password field type)
 *   custscript_wal_multi_test_saved_search     - internal ID of the same tire item saved search
 *                                                 wm_mr_tire_upload.js / wm_sl_test_upload.js use
 * 
 * TODO: construction type hardcoded as 'Radial', may pull this data from a NetSuite field eventually. 
*/
define(
    ['N/ui/serverWidget', 'N/record', 'N/runtime', 'N/https', 'N/encode', 'N/search', 'N/log', 'N/crypto/random'],
    (serverWidget, record, runtime, https, encode, search, log, random) => {

        const BASE_URL = 'https://sandbox.walmartapis.com';
        const FEED_SPEC_VERSION = '5.0.20260608-18_15_07-api';
        const MAX_ITEMS = 10;

        const FEED_TYPE = 'MP_ITEM';
        const WALMART_ITEM_TYPE = 'Tires';

        const FEED_RECORD = {
            TYPE: 'customrecord_wal_feed_submission',
            FIELDS: {
                FEED_ID: 'custrecord_wal_feed_id',
                STATUS: 'custrecord_wal_feed_status',
                ENVIRONMENT: 'custrecord_wal_feed_env',
                ITEM_COUNT: 'custrecord_wal_feed_item_count',
                SUBMITTED_DATE: 'custrecord_wal_feed_submitted_date',
                BUCKET: 'custrecord_wal_feed_bucket',
                DETAILS: 'custrecord_wal_feed_details',
                CORRELATION_ID: 'custrecord_wal_feed_correlation_id',
                FEED_TYPE: 'custrecord_wal_feed_type',
                ITEM_TYPE: 'custrecord_wal_feed_item_type',
                SKUS: 'custrecord_wal_feed_skus'
            }
        };

        // Same saved-search column labels as wm_mr_tire_upload.js's COLUMNS --
        // duplicated so this tool matches that field mapping exactly rather
        // than guessing raw NetSuite field IDs.
        const COLUMNS = {
            ORDERABLE: {
                SKU: 'itemid',
                // PRODUCT_ID_UPC/GTIN: kept only for parity with wm_mr_tire_upload.js's
                // COLUMNS -- unused here since productIdentifiers is always a generated
                // test value (see buildTestWalmartItem()), not real (sometimes-malformed)
                // NetSuite data. COUNTRY_OF_ORIGIN below IS read -- see mapCountryOfOrigin().
                PRODUCT_ID_UPC: 'custitemtire_upc',
                PRODUCT_ID_GTIN: 'upccode',
                SHIPPING_WEIGHT: 'custitemproduct_ship_weight',
                COUNTRY_OF_ORIGIN: 'countryofmanufacture',
                PRICE: 'pricing.unitprice'
            },
            VISIBLE: {
                PRODUCT_NAME: 'salesdescription',
                // Kept for parity with wm_mr_tire_upload.js's COLUMNS -- unused here since
                // shortDescription is generated by buildShortDescription(), not sourced directly.
                SHORT_DESCRIPTION: 'salesdescription',
                ASSEMBLED_PRODUCT_WEIGHT: 'custitem48',
                TIRE_LOAD_INDEX: 'custitem_load_index',
                TIRE_SPEED_RATING: 'custitem_speed_rating',
                BRAND: 'custitem_inv_group',
                MANUFACTURER: 'manufacturer',
                MAIN_IMAGE_URL: 'custitem_scs_image_url',
                TIRE_TERRAIN: 'custitem_terrain_amani',
                TIRE_TYPE: 'custitem_tire_type_amani',
                TIRE_WIDTH: 'custitem_ewd_raw_size_1',
                TIRE_HEIGHT: 'custitem_ewd_raw_size_4',
                ASPECT_RATIO: 'custitem_ewd_raw_size_2',
                VEHICLE_TYPE: 'custitem_vehicle_category',
                TIRE_DIAMETER: 'custitem_ewd_raw_size_3',
                IS_RUN_FLAT: 'custitem_tire_run_flat',
                TIRE_SIZE: 'custitem_tire_size_amani',
                UNIFORM_TIRE_QUALITY_GRADE: 'custitemutqg',
                TIRE_TREADWEAR_RATING: 'custitemutqg',
                MILEAGE_WARRANTY: 'custitem_mileage_warranty',
                MANUFACTURER_PART_NUMBER: 'itemid',
                TIRE_SEASON: 'custitem_tire_season',
                ELECTRIC_VEHICLE_TIRE: 'custitem_electric_vehicle_tire',
                WARRANTY_URL: '',
                GROUP: 'custitem_group',
                DIMENSION_UNIT_TYPE: 'custitem_tire_dim_unit_type',
                TIRE_CLASS: 'custitem_tire_class',
                SECONDARY_IMAGE_FACE: 'CUSTITEM_PRODUCT_IMAGE_RECORD.custrecord_pil_face_jpg',
                SECONDARY_IMAGE_SIDE: 'CUSTITEM_PRODUCT_IMAGE_RECORD.custrecord_pil_side_jpg'
            }
        };

        // Same NetSuite -> Walmart enum translation as wm_mr_tire_upload.js / wm_sl_test_upload.js.
        const TIRE_TYPE_FIELD_MAPPING = {
            'Ultra High Performance (UHP)': { walmartField: 'tireType', values: ['Performance Tires'] },
            'Light Truck (LT)': { walmartField: 'tireType', values: ['Light Truck Tires'] },
            'Off-Road / All Terrain': { walmartField: 'tireTerrain', values: ['Off-Road', 'All-Terrain'] },
            'A/T': { walmartField: 'tireTerrain', values: ['All-Terrain'] },
            'M/T': { walmartField: 'tireTerrain', values: ['Mud Terrain'] },
            'X/T': { walmartField: 'tireTerrain', values: ['Off-Road'] },
            'R/T': { walmartField: 'tireTerrain', values: ['Off-Road'] }
        };
        // custitem_tire_class -> Walmart tireType enum. Merged in alongside
        // whatever custitem_tire_type_amani's tags produce
        const TIRE_CLASS_TO_TIRE_TYPE = {
            'LT': 'Light Truck Tires',
            'P': 'Passenger Car Tires',
            'ST': 'Trailer Tires'
        };
        const VEHICLE_TYPE_MAPPING = {
            'Car': ['Car'],
            'Passenger Car': ['Car'],
            'Classic Car': ['Car'],
            'Car & SUV': ['Car', 'Sport Utility Vehicle'],
            'Car, Truck & SUV': ['Car', 'Light Truck', 'Sport Utility Vehicle'],
            'Truck & SUV': ['Light Truck', 'Sport Utility Vehicle'],
            'Dually': ['Light Truck'],
            'Offroad': ['Sport Utility Vehicle'],
            'HC': ['Light Truck']
        };
        const TIRE_TYPES_REQUIRING_LOAD_SPEED_CONSTRUCTION = [
            'Crossover & Minivan Tires', 'Light Truck & SUV Tires', 'Light Truck Tires',
            'Passenger Car Tires', 'Performance Tires', 'Sport Utility Vehicle Tires'
        ];
        const TIRE_TYPES_REQUIRING_UNIFORM_QUALITY_GRADE = ['Light Truck Tires', 'Passenger Car Tires'];
        const VEHICLE_TYPES_REQUIRING_TREADWEAR_RATING = ['Car', 'Light Truck', 'Sport Utility Vehicle'];
        const VEHICLE_TYPES_REQUIRING_MILEAGE_WARRANTY = ['Car', 'Light Truck'];

        // Fixed placeholder values -- deliberately not realistic, just schema-valid,
        // so a submission failure means the *pipeline* is broken, not "this item's
        // data was incomplete".
        const PLACEHOLDERS = {
            productName: 'TEST TIRE - PLACEHOLDER PRODUCT NAME',
            brand: 'Test Brand',
            manufacturer: 'Test Manufacturer',
            manufacturerPartNumber: 'TEST-MPN-0000',
            // No shortDescription entry -- always generated by buildShortDescription()
            // instead (see buildTestWalmartItem()), same as keyFeatures below.
            mainImageUrl: 'https://example.com/placeholder-main-image.jpg',
            productSecondaryImageURL: ['https://example.com/placeholder-secondary-1.jpg', 'https://example.com/placeholder-secondary-2.jpg'],
            tireSize: '225/60R18',
            tireSeason: 'All-Season',
            tireTerrain: ['Highway Terrain'],
            tireType: ['Passenger Car Tires'],
            vehicleType: ['Car'],
            isRunFlat: 'No',
            electric_vehicle_tire: 'No',
            warrantyURL: 'https://example.com/placeholder-warranty-info',
            prop65WarningText: 'WARNING: This product can expose you to chemicals which are known '
                + 'to the State of California to cause cancer and birth defects or other '
                + 'reproductive harm. For more information go to www.P65Warnings.ca.gov.',
            tireAspectRatio: '60',
            tireLoadIndex: '91',
            tireSpeedRating: 'H',
            uniformTireQualityGrade: '400 A A',
            tireTreadwearRating: '400'
            // No countryOfOrigin entry -- handled directly in buildTestWalmartItem()'s
            // orderable construction via mapCountryOfOrigin()/COUNTRY_CODE_TO_NAME (real
            // countryofmanufacture translated to Walmart's enum spelling, falling back
            // to "United States" only when blank/unmapped).
        };

        // ---------------------------------------------------------------
        // shortDescription synthesis -- Walmart's Tires.json requires
        // shortDescription >= 60 words (@minimumWordCount=60;
        // @recommendedWordCount=75), which no NetSuite field comes close to
        // alone (salesdescription is a short sales blurb, not a paragraph).
        // Added HERE FIRST (not yet in wm_mr_tire_upload.js) so generated
        // output can be reviewed against real sandbox items before porting
        // to the production upload path. The lookup tables below are the
        // sentence-source versions of wm_mr_tire_upload.js's KEY_FEATURES_BY_*
        // constants (which build bullet-style keyFeatures from the same
        // attributes) -- duplicated per this project's self-contained-script
        // convention.
        // ---------------------------------------------------------------

        const KEY_FEATURES_BY_TIRE_TYPE = {
            'Commercial Tires': 'Heavy-duty construction built to handle demanding commercial routes and daily loads',
            'Crossover & Minivan Tires': 'Balanced construction supports the extra weight of passengers and cargo with confidence',
            'Golf Tires': 'Wide tread design distributes weight evenly for gentle handling on grass and turf',
            'Lawn & Garden Tires': 'Aggressive turf tread grips grass, dirt, and gravel without tearing up your lawn',
            'Light Truck & SUV Tires': 'Rugged construction is built to handle towing, hauling, and off-road demands',
            'Light Truck Tires': 'Reinforced construction is built for towing, hauling, and heavy payloads',
            'Passenger Car Tires': 'Smooth, quiet ride tuned for everyday commuting and highway driving',
            'Performance Tires': 'Responsive handling and precise steering feedback for spirited driving',
            'Racing Tires': 'Ultra-high-speed-rated construction built for maximum performance on the track',
            'Sport Utility Vehicle Tires': 'Confident all-terrain traction handles pavement, gravel, and light off-road trails',
            'Temporary Spare Tire': 'Compact, space-saving design keeps your vehicle prepared for emergencies',
            'Touring Tires': 'Smooth, quiet ride designed for comfortable long-distance highway driving',
            'Trailer Tires': 'Reinforced sidewalls are built to handle the sway and stress of towing'
        };

        const KEY_FEATURES_BY_SPEED_RATING = {
            'A1': 'A1-rated for speeds up to 3 mph', 'A2': 'A2-rated for speeds up to 6 mph',
            'A3': 'A3-rated for speeds up to 9 mph', 'A4': 'A4-rated for speeds up to 12 mph',
            'A5': 'A5-rated for speeds up to 15 mph', 'A6': 'A6-rated for speeds up to 18 mph',
            'A7': 'A7-rated for speeds up to 21 mph', 'A8': 'A8-rated for speeds up to 24 mph',
            'B': 'B-rated for speeds up to 31 mph', 'C': 'C-rated for speeds up to 37 mph',
            'D': 'D-rated for speeds up to 40 mph', 'E': 'E-rated for speeds up to 43 mph',
            'F': 'F-rated for speeds up to 50 mph', 'G': 'G-rated for speeds up to 56 mph',
            'J': 'J-rated for speeds up to 62 mph', 'K': 'K-rated for speeds up to 68 mph',
            'L': 'L-rated for speeds up to 75 mph', 'M': 'M-rated for speeds up to 81 mph',
            'N': 'N-rated for speeds up to 87 mph', 'P': 'P-rated for speeds up to 93 mph',
            'Q': 'Q-rated for speeds up to 99 mph', 'R': 'R-rated for speeds up to 106 mph',
            'S': 'S-rated for speeds up to 112 mph', 'T': 'T-rated for speeds up to 118 mph',
            'U': 'U-rated for speeds up to 124 mph', 'H': 'H-rated for speeds up to 130 mph',
            'V': 'V-rated for speeds up to 149 mph', 'Z': 'Z-rated for speeds of 149+ mph',
            'ZR': 'ZR-rated for speeds of 149+ mph', 'W': 'W-rated for speeds up to 168 mph',
            '(W)': '(W)-rated for speeds of 168+ mph', 'Y': 'Y-rated for speeds up to 186 mph',
            '(Y)': '(Y)-rated for speeds of 186+ mph'
        };

        // Max load per index is the standard ETRTO/TRA tire load index chart
        // (single-tire load, lbs), sourced from Wikipedia's "Tire code" load
        // index table -- same table as wm_mr_tire_upload.js's KEY_FEATURES_BY_LOAD_INDEX.
        const KEY_FEATURES_BY_LOAD_INDEX = {
            '0': 'Load index 0 - rated to carry up to 99 lbs per tire', '1': 'Load index 1 - rated to carry up to 102 lbs per tire',
            '2': 'Load index 2 - rated to carry up to 105 lbs per tire', '3': 'Load index 3 - rated to carry up to 107 lbs per tire',
            '4': 'Load index 4 - rated to carry up to 110 lbs per tire', '5': 'Load index 5 - rated to carry up to 114 lbs per tire',
            '6': 'Load index 6 - rated to carry up to 117 lbs per tire', '7': 'Load index 7 - rated to carry up to 120 lbs per tire',
            '8': 'Load index 8 - rated to carry up to 123 lbs per tire', '9': 'Load index 9 - rated to carry up to 128 lbs per tire',
            '10': 'Load index 10 - rated to carry up to 132 lbs per tire', '11': 'Load index 11 - rated to carry up to 136 lbs per tire',
            '12': 'Load index 12 - rated to carry up to 139 lbs per tire', '13': 'Load index 13 - rated to carry up to 143 lbs per tire',
            '14': 'Load index 14 - rated to carry up to 148 lbs per tire', '15': 'Load index 15 - rated to carry up to 152 lbs per tire',
            '16': 'Load index 16 - rated to carry up to 157 lbs per tire', '17': 'Load index 17 - rated to carry up to 161 lbs per tire',
            '18': 'Load index 18 - rated to carry up to 165 lbs per tire', '19': 'Load index 19 - rated to carry up to 171 lbs per tire',
            '20': 'Load index 20 - rated to carry up to 176 lbs per tire', '21': 'Load index 21 - rated to carry up to 182 lbs per tire',
            '22': 'Load index 22 - rated to carry up to 187 lbs per tire', '23': 'Load index 23 - rated to carry up to 193 lbs per tire',
            '24': 'Load index 24 - rated to carry up to 198 lbs per tire', '25': 'Load index 25 - rated to carry up to 204 lbs per tire',
            '26': 'Load index 26 - rated to carry up to 209 lbs per tire', '27': 'Load index 27 - rated to carry up to 215 lbs per tire',
            '28': 'Load index 28 - rated to carry up to 220 lbs per tire', '29': 'Load index 29 - rated to carry up to 227 lbs per tire',
            '30': 'Load index 30 - rated to carry up to 234 lbs per tire', '31': 'Load index 31 - rated to carry up to 240 lbs per tire',
            '32': 'Load index 32 - rated to carry up to 247 lbs per tire', '33': 'Load index 33 - rated to carry up to 254 lbs per tire',
            '34': 'Load index 34 - rated to carry up to 260 lbs per tire', '35': 'Load index 35 - rated to carry up to 267 lbs per tire',
            '36': 'Load index 36 - rated to carry up to 276 lbs per tire', '37': 'Load index 37 - rated to carry up to 282 lbs per tire',
            '38': 'Load index 38 - rated to carry up to 291 lbs per tire', '39': 'Load index 39 - rated to carry up to 300 lbs per tire',
            '40': 'Load index 40 - rated to carry up to 309 lbs per tire', '41': 'Load index 41 - rated to carry up to 320 lbs per tire',
            '42': 'Load index 42 - rated to carry up to 331 lbs per tire', '43': 'Load index 43 - rated to carry up to 342 lbs per tire',
            '44': 'Load index 44 - rated to carry up to 353 lbs per tire', '45': 'Load index 45 - rated to carry up to 364 lbs per tire',
            '46': 'Load index 46 - rated to carry up to 375 lbs per tire', '47': 'Load index 47 - rated to carry up to 386 lbs per tire',
            '48': 'Load index 48 - rated to carry up to 397 lbs per tire', '49': 'Load index 49 - rated to carry up to 408 lbs per tire',
            '50': 'Load index 50 - rated to carry up to 419 lbs per tire', '51': 'Load index 51 - rated to carry up to 430 lbs per tire',
            '52': 'Load index 52 - rated to carry up to 441 lbs per tire', '53': 'Load index 53 - rated to carry up to 454 lbs per tire',
            '54': 'Load index 54 - rated to carry up to 467 lbs per tire', '55': 'Load index 55 - rated to carry up to 481 lbs per tire',
            '56': 'Load index 56 - rated to carry up to 494 lbs per tire', '57': 'Load index 57 - rated to carry up to 507 lbs per tire',
            '58': 'Load index 58 - rated to carry up to 520 lbs per tire', '59': 'Load index 59 - rated to carry up to 536 lbs per tire',
            '60': 'Load index 60 - rated to carry up to 551 lbs per tire', '61': 'Load index 61 - rated to carry up to 567 lbs per tire',
            '62': 'Load index 62 - rated to carry up to 584 lbs per tire', '63': 'Load index 63 - rated to carry up to 600 lbs per tire',
            '64': 'Load index 64 - rated to carry up to 617 lbs per tire', '65': 'Load index 65 - rated to carry up to 639 lbs per tire',
            '66': 'Load index 66 - rated to carry up to 661 lbs per tire', '67': 'Load index 67 - rated to carry up to 677 lbs per tire',
            '68': 'Load index 68 - rated to carry up to 694 lbs per tire', '69': 'Load index 69 - rated to carry up to 716 lbs per tire',
            '70': 'Load index 70 - rated to carry up to 739 lbs per tire', '71': 'Load index 71 - rated to carry up to 761 lbs per tire',
            '72': 'Load index 72 - rated to carry up to 783 lbs per tire', '73': 'Load index 73 - rated to carry up to 805 lbs per tire',
            '74': 'Load index 74 - rated to carry up to 827 lbs per tire', '75': 'Load index 75 - rated to carry up to 852 lbs per tire',
            '76': 'Load index 76 - rated to carry up to 882 lbs per tire', '77': 'Load index 77 - rated to carry up to 908 lbs per tire',
            '78': 'Load index 78 - rated to carry up to 937 lbs per tire', '79': 'Load index 79 - rated to carry up to 963 lbs per tire',
            '80': 'Load index 80 - rated to carry up to 992 lbs per tire', '81': 'Load index 81 - rated to carry up to 1,019 lbs per tire',
            '82': 'Load index 82 - rated to carry up to 1,047 lbs per tire', '83': 'Load index 83 - rated to carry up to 1,074 lbs per tire',
            '84': 'Load index 84 - rated to carry up to 1,102 lbs per tire', '85': 'Load index 85 - rated to carry up to 1,135 lbs per tire',
            '86': 'Load index 86 - rated to carry up to 1,168 lbs per tire', '87': 'Load index 87 - rated to carry up to 1,201 lbs per tire',
            '88': 'Load index 88 - rated to carry up to 1,235 lbs per tire', '89': 'Load index 89 - rated to carry up to 1,279 lbs per tire',
            '90': 'Load index 90 - rated to carry up to 1,323 lbs per tire', '91': 'Load index 91 - rated to carry up to 1,356 lbs per tire',
            '92': 'Load index 92 - rated to carry up to 1,389 lbs per tire', '93': 'Load index 93 - rated to carry up to 1,433 lbs per tire',
            '94': 'Load index 94 - rated to carry up to 1,477 lbs per tire', '95': 'Load index 95 - rated to carry up to 1,521 lbs per tire',
            '96': 'Load index 96 - rated to carry up to 1,565 lbs per tire', '97': 'Load index 97 - rated to carry up to 1,609 lbs per tire',
            '98': 'Load index 98 - rated to carry up to 1,653 lbs per tire', '99': 'Load index 99 - rated to carry up to 1,709 lbs per tire',
            '100': 'Load index 100 - rated to carry up to 1,764 lbs per tire', '101': 'Load index 101 - rated to carry up to 1,819 lbs per tire',
            '102': 'Load index 102 - rated to carry up to 1,874 lbs per tire', '103': 'Load index 103 - rated to carry up to 1,929 lbs per tire',
            '104': 'Load index 104 - rated to carry up to 1,984 lbs per tire', '105': 'Load index 105 - rated to carry up to 2,039 lbs per tire',
            '106': 'Load index 106 - rated to carry up to 2,094 lbs per tire', '107': 'Load index 107 - rated to carry up to 2,149 lbs per tire',
            '108': 'Load index 108 - rated to carry up to 2,205 lbs per tire', '109': 'Load index 109 - rated to carry up to 2,271 lbs per tire',
            '110': 'Load index 110 - rated to carry up to 2,337 lbs per tire', '111': 'Load index 111 - rated to carry up to 2,403 lbs per tire',
            '112': 'Load index 112 - rated to carry up to 2,469 lbs per tire', '113': 'Load index 113 - rated to carry up to 2,535 lbs per tire',
            '114': 'Load index 114 - rated to carry up to 2,601 lbs per tire', '115': 'Load index 115 - rated to carry up to 2,679 lbs per tire',
            '116': 'Load index 116 - rated to carry up to 2,756 lbs per tire', '117': 'Load index 117 - rated to carry up to 2,833 lbs per tire',
            '118': 'Load index 118 - rated to carry up to 2,910 lbs per tire', '119': 'Load index 119 - rated to carry up to 2,998 lbs per tire',
            '120': 'Load index 120 - rated to carry up to 3,086 lbs per tire', '121': 'Load index 121 - rated to carry up to 3,197 lbs per tire',
            '122': 'Load index 122 - rated to carry up to 3,307 lbs per tire', '123': 'Load index 123 - rated to carry up to 3,417 lbs per tire',
            '124': 'Load index 124 - rated to carry up to 3,527 lbs per tire', '125': 'Load index 125 - rated to carry up to 3,638 lbs per tire',
            '126': 'Load index 126 - rated to carry up to 3,748 lbs per tire', '127': 'Load index 127 - rated to carry up to 3,858 lbs per tire',
            '128': 'Load index 128 - rated to carry up to 3,968 lbs per tire', '129': 'Load index 129 - rated to carry up to 4,079 lbs per tire',
            '130': 'Load index 130 - rated to carry up to 4,189 lbs per tire', '131': 'Load index 131 - rated to carry up to 4,289 lbs per tire',
            '132': 'Load index 132 - rated to carry up to 4,409 lbs per tire', '133': 'Load index 133 - rated to carry up to 4,541 lbs per tire',
            '134': 'Load index 134 - rated to carry up to 4,674 lbs per tire', '135': 'Load index 135 - rated to carry up to 4,806 lbs per tire',
            '136': 'Load index 136 - rated to carry up to 4,938 lbs per tire', '137': 'Load index 137 - rated to carry up to 5,071 lbs per tire',
            '138': 'Load index 138 - rated to carry up to 5,203 lbs per tire', '139': 'Load index 139 - rated to carry up to 5,357 lbs per tire',
            '140': 'Load index 140 - rated to carry up to 5,512 lbs per tire', '141': 'Load index 141 - rated to carry up to 5,677 lbs per tire',
            '142': 'Load index 142 - rated to carry up to 5,842 lbs per tire', '143': 'Load index 143 - rated to carry up to 6,008 lbs per tire',
            '144': 'Load index 144 - rated to carry up to 6,173 lbs per tire', '145': 'Load index 145 - rated to carry up to 6,393 lbs per tire',
            '146': 'Load index 146 - rated to carry up to 6,614 lbs per tire', '147': 'Load index 147 - rated to carry up to 6,779 lbs per tire',
            '148': 'Load index 148 - rated to carry up to 6,844 lbs per tire', '149': 'Load index 149 - rated to carry up to 7,165 lbs per tire',
            '150': 'Load index 150 - rated to carry up to 7,390 lbs per tire', '152': 'Load index 152 - rated to carry up to 7,830 lbs per tire',
            '156': 'Load index 156 - rated to carry up to 8,820 lbs per tire', '160': 'Load index 160 - rated to carry up to 9,920 lbs per tire'
        };

        const RUN_FLAT_KEY_FEATURE = 'Run-flat technology keeps you moving at reduced speed for up to 10 miles after a puncture';

        // Construction/spec-angle counterpart to SHORT_DESC_ELECTRIC_VEHICLE_SENTENCE
        // below -- same boolean-flag pattern as RUN_FLAT_KEY_FEATURE/
        // SHORT_DESC_RUN_FLAT_SENTENCE, so see that pair's comment for why the two
        // surfaces get distinct wording for the same fact.
        const ELECTRIC_VEHICLE_KEY_FEATURE = 'Reinforced, low-rolling-resistance construction built to handle the extra weight of an EV battery while helping preserve range';

        // tireTerrain/tireSeason sentence-lookups for keyFeatures -- same content/
        // wording as wm_mr_tire_upload.js's KEY_FEATURES_BY_TIRE_TERRAIN/
        // KEY_FEATURES_BY_TIRE_SEASON (duplicated per this project's self-contained-
        // script convention). No shortDescription equivalent of these two exists --
        // season/terrain are folded into buildShortDescription()'s intro sentence as
        // adjectives instead (see that function), so there's nothing to dedupe against.
        const KEY_FEATURES_BY_TIRE_TERRAIN = {
            'All-Terrain': 'All-Terrain tread design tackles pavement, gravel, and dirt with confidence',
            'Highway Terrain': 'Highway Terrain tread delivers a smooth, quiet ride built for daily pavement driving',
            'Ice': 'Specialized siping and compound bite into icy surfaces for dependable traction',
            'Mud Terrain': 'Aggressive Mud Terrain tread claws through deep mud and clears debris on the go',
            'Off-Road': 'Off-Road tread pattern is built to handle rocks, ruts, and rugged trails',
            'Sand': 'Tread design floats over loose sand instead of digging in and losing traction',
            'Snow': 'Snow-optimized tread and compound grip confidently in cold, slick conditions'
        };

        const KEY_FEATURES_BY_TIRE_SEASON = {
            'All-Season': 'All-Season tread compound delivers confident grip year-round in wet and dry conditions',
            'Summer': 'Summer tread compound maximizes grip and handling in warm, dry conditions',
            'Winter': 'Winter tread compound and biting edges grip confidently in snow, ice, and cold temperatures'
        };

        // Generic fallback bullets, used to pad keyFeatures toward the schema's
        // minItems: 5 when too few of the lookups above matched -- same list as
        // wm_mr_tire_upload.js's GENERIC_KEY_FEATURES.
        const GENERIC_KEY_FEATURES = [
            'Precision-engineered construction delivers consistent, dependable performance mile after mile',
            'Manufactured to meet strict DOT safety and quality standards',
            'Every tire is quality-inspected before it leaves the factory',
            'Straightforward mounting and balancing at any professional tire shop',
            'Built with durable materials designed to stand up to daily wear',
            'A dependable choice trusted by drivers for everyday performance'
        ];

        /**
         * Synthesizes keyFeatures bullets from the item's FINAL attribute values --
         * same lookup-and-pad logic as wm_mr_tire_upload.js's buildKeyFeatures(),
         * added HERE FIRST so generated output can be reviewed against real sandbox
         * items before porting to that file's production upload path (same reasoning
         * as buildShortDescription() below). Called from buildTestWalmartItem() AFTER
         * applyPlaceholders(), same timing as buildShortDescription(), so a real item
         * missing tireSpeedRating/tireLoadIndex (only placeholder-filled conditionally,
         * later than the other tiresVisible fields) still gets bullets consistent with
         * what's actually submitted.
         * @param {Object} fields
         * @param {string[]} fields.tireType
         * @param {string[]} fields.tireTerrain
         * @param {string} fields.tireSpeedRating
         * @param {string} fields.tireLoadIndex
         * @param {string} fields.tireSeason
         * @param {string} fields.isRunFlat
         * @param {string} fields.electricVehicleTire
         * @returns {string[]}
         */
        function buildKeyFeatures(fields) {
            const bullets = [];
            fields.tireType.forEach((t) => { if (KEY_FEATURES_BY_TIRE_TYPE[t]) bullets.push(KEY_FEATURES_BY_TIRE_TYPE[t]); });
            fields.tireTerrain.forEach((t) => { if (KEY_FEATURES_BY_TIRE_TERRAIN[t]) bullets.push(KEY_FEATURES_BY_TIRE_TERRAIN[t]); });
            if (KEY_FEATURES_BY_SPEED_RATING[fields.tireSpeedRating]) bullets.push(KEY_FEATURES_BY_SPEED_RATING[fields.tireSpeedRating]);
            if (KEY_FEATURES_BY_LOAD_INDEX[fields.tireLoadIndex]) bullets.push(KEY_FEATURES_BY_LOAD_INDEX[fields.tireLoadIndex]);
            if (KEY_FEATURES_BY_TIRE_SEASON[fields.tireSeason]) bullets.push(KEY_FEATURES_BY_TIRE_SEASON[fields.tireSeason]);
            if (fields.isRunFlat === 'Yes') bullets.push(RUN_FLAT_KEY_FEATURE);
            if (fields.electricVehicleTire === 'Yes') bullets.push(ELECTRIC_VEHICLE_KEY_FEATURE);

            const deduped = Array.from(new Set(bullets));
            for (let i = 0; deduped.length < 5 && i < GENERIC_KEY_FEATURES.length; i++) {
                if (!deduped.includes(GENERIC_KEY_FEATURES[i])) deduped.push(GENERIC_KEY_FEATURES[i]);
            }
            return deduped;
        }

        // Generic filler sentences for buildShortDescription() -- deliberately
        // distinct wording from keyFeatures' lookups/GENERIC_KEY_FEATURES above,
        // used to pad buildShortDescription() toward the 60-word minimum when an
        // item's attributes don't produce enough sentences on their own.
        const GENERIC_DESCRIPTION_FILLERS = [
            'Every tire is engineered with precision and backed by rigorous quality control, so it performs consistently mile after mile.',
            'It meets strict DOT safety standards and is inspected before it ever leaves the factory.',
            'Mounting and balancing are quick and straightforward at any professional tire shop.',
            'Durable materials and dependable construction help it stand up to daily wear and tear.',
            'It is a trusted choice for drivers who expect reliable performance without surprises.'
        ];

        /** Word count, splitting on any run of whitespace. */
        function countWords(text) {
            return String(text || '').trim().split(/\s+/).filter(Boolean).length;
        }

        /** Joins a string array as a natural-language list ("a, b, and c"). */
        function joinWithAnd(items) {
            if (items.length === 0) return '';
            if (items.length === 1) return items[0];
            if (items.length === 2) return `${items[0]} and ${items[1]}`;
            return `${items.slice(0, -1).join(', ')}, and ${items[items.length - 1]}`;
        }

        // Walmart's vehicleType enum values, restated the way tire retail
        // copy actually talks about them ("light trucks and SUVs", not
        // "Light Truck and Sport Utility Vehicle use") -- see buildShortDescription().
        const VEHICLE_TYPE_PLURAL = {
            'Car': 'cars',
            'Light Truck': 'light trucks',
            'Sport Utility Vehicle': 'SUVs'
        };

        /** "a" before a consonant sound, "an" before a vowel sound (e.g. "an all-season", "a summer"). */
        function article(word) {
            return /^[aeiou]/i.test(word || '') ? 'an' : 'a';
        }

        /** Deterministic (non-cryptographic) string hash -- same SKU always yields the same variety picks. */
        function hashString(str) {
            let hash = 0;
            const s = String(str || '');
            for (let i = 0; i < s.length; i++) {
                hash = (hash * 31 + s.charCodeAt(i)) & 0x7fffffff;
            }
            return hash;
        }

        /** Seeded Fisher-Yates shuffle -- deterministic per seed, not true randomness, so re-running the same item reproduces the same order. */
        function seededShuffle(array, seed) {
            const arr = array.slice();
            let state = seed || 1;
            const next = () => {
                state = (state * 1103515245 + 12345) & 0x7fffffff;
                return state;
            };
            for (let i = arr.length - 1; i > 0; i--) {
                const j = next() % (i + 1);
                [arr[i], arr[j]] = [arr[j], arr[i]];
            }
            return arr;
        }

        /** Thousands-separator formatting (e.g. 60000 -> "60,000") without depending on toLocaleString()'s locale behavior. */
        function formatNumber(n) {
            return String(n).replace(/\B(?=(\d{3})+(?!\d))/g, ',');
        }

        // Multiple phrasings so a batch of items doesn't repeat the exact
        // same mileage-warranty sentence -- picked deterministically per
        // item (see buildShortDescription()'s seed), not randomly.
        const MILEAGE_WARRANTY_SENTENCES = [
            (miles) => `Backed by a ${miles}-mile treadwear warranty.`,
            (miles) => `A ${miles}-mile treadwear warranty backs it for the long haul.`,
            (miles) => `Its treadwear warranty covers up to ${miles} miles.`
        ];

        // Multiple closing-flourish phrasings (only used when fields.group
        // is present) -- same reasoning as MILEAGE_WARRANTY_SENTENCES above.
        const CLOSING_LINE_SENTENCES = [
            (group) => `Built with the latest tire technology, the ${group} delivers performance you can rely on mile after mile.`,
            (group) => `From daily commutes to demanding drives, the ${group} is engineered to perform when it matters most.`,
            (group) => `The ${group} combines proven engineering with dependable materials for a tire you can trust.`,
            (group) => `Backed by rigorous engineering, the ${group} is built to deliver consistent performance for the long haul.`,
            (group) => `Whatever the road ahead, the ${group} is built to get you there with confidence.`
        ];

        // tireType, tireSpeedRating, tireLoadIndex, and isRunFlat all also drive a
        // buildKeyFeatures() bullet (see above) -- KEY_FEATURES_BY_TIRE_TYPE/
        // SPEED_RATING/LOAD_INDEX/RUN_FLAT_KEY_FEATURE stay in scope here only as the
        // SOURCE of the underlying fact (the type label, the mph number, the lbs
        // number), never rendered verbatim into the description. Each gets its own
        // shortDescription-only phrasing below, on a different angle (use-case/
        // benefit) than the keyFeatures bullet's angle (construction/spec), so a
        // reviewer reading both for the same item sees two takes on the fact, not
        // the same sentence twice.

        // Same use-case framing as KEY_FEATURES_BY_TIRE_TYPE's keys, worded as
        // benefit-facing prose instead of that table's construction/engineering
        // framing -- see comment above.
        const SHORT_DESC_TIRE_TYPE_SENTENCES = {
            'Commercial Tires': "It's built for commercial-route duty, standing up to daily loads without missing a beat.",
            'Crossover & Minivan Tires': "It's tuned for crossover and minivan use, handling the extra weight of passengers and cargo with ease.",
            'Golf Tires': "It's designed for the golf course, spreading weight evenly so it won't tear up the turf.",
            'Lawn & Garden Tires': "It's suited for lawn and garden equipment, gripping grass and gravel without chewing up your yard.",
            'Light Truck & SUV Tires': "It's suited to light-truck and SUV duty, from towing and hauling to the occasional dirt road.",
            'Light Truck Tires': "It's built for light-truck work, standing up to towing and heavy payloads.",
            'Passenger Car Tires': "It's tuned for everyday passenger-car driving, commuting and highway miles alike.",
            'Performance Tires': "It's tuned for performance driving, with sharp steering feedback when you push it.",
            'Racing Tires': "It's built for the track, engineered around ultra-high-speed performance.",
            'Sport Utility Vehicle Tires': "It's suited to SUV duty, handling pavement, gravel, and the occasional light trail.",
            'Temporary Spare Tire': "It's a compact spare, made to get you safely to a shop rather than for daily driving.",
            'Touring Tires': "It's tuned for touring, built for long highway stretches in comfort and quiet.",
            'Trailer Tires': "It's built for trailer duty, with sidewalls reinforced against the sway and stress of towing."
        };

        // Benefit-facing counterpart to RUN_FLAT_KEY_FEATURE's spec-facing bullet.
        const SHORT_DESC_RUN_FLAT_SENTENCE = "It's also run-flat rated, so a puncture won't leave you stranded roadside.";

        // Benefit-facing counterpart to ELECTRIC_VEHICLE_KEY_FEATURE's spec-facing bullet.
        const SHORT_DESC_ELECTRIC_VEHICLE_SENTENCE = "It's also EV-rated, quiet and tough enough to carry an electric vehicle's extra battery weight without sacrificing range.";

        /** Pulls the mph number (and whether it's an open-ended "149+" style rating) out of a KEY_FEATURES_BY_SPEED_RATING sentence. */
        function parseSpeedRatingMph(sentence) {
            const match = /(\d+)(\+)?\s*mph/.exec(sentence || '');
            return match ? { mph: match[1], plus: !!match[2] } : null;
        }

        /** Pulls the "lbs per tire" number out of a KEY_FEATURES_BY_LOAD_INDEX sentence. */
        function parseLoadIndexLbs(sentence) {
            const match = /up to ([\d,]+) lbs/.exec(sentence || '');
            return match ? match[1] : null;
        }

        // Multiple phrasings so a batch of items with the same rating doesn't read
        // as the same sentence with only the number changed -- same reasoning/
        // seeding as MILEAGE_WARRANTY_SENTENCES above.
        const SPEED_RATING_SHORT_DESC_SENTENCES = [
            (letter, mph, plus) => (plus
                ? `Its ${letter} speed rating certifies it for sustained speeds of ${mph}+ mph.`
                : `Its ${letter} speed rating certifies it for sustained speeds up to ${mph} mph.`),
            (letter, mph, plus) => (plus
                ? `With a ${letter} speed rating, it's built to handle sustained speeds beyond ${mph} mph.`
                : `With a ${letter} speed rating, it's built to safely handle speeds up to ${mph} mph.`)
        ];

        const LOAD_INDEX_SHORT_DESC_SENTENCES = [
            (lbs) => `It carries a load index rated to support up to ${lbs} lbs per tire.`,
            (lbs) => `Its load index supports up to ${lbs} lbs per tire, so it won't be the weak link under load.`
        ];

        /**
         * Synthesizes a Walmart-compliant shortDescription paragraph from the
         * item's FINAL tireType/tireTerrain/vehicleType/etc -- called AFTER
         * applyPlaceholders() so a real item missing some attributes still
         * gets a description consistent with what's actually submitted (e.g.
         * if tireType had to be placeholder-filled, the description reflects
         * that placeholder, not a blank).
         *
         * Modeled on real tire-retailer copy (e.g. "The LXHT-206 from Lexani
         * is an all-season, highway terrain tire that's designed for use on
         * light trucks and SUVs...") rather than a flat list of independent
         * feature bullets -- season and terrain are folded into the intro
         * sentence as adjectives instead of getting their own KEY_FEATURES_BY_*
         * sentence, since naming "all-season" up front and then separately
         * stating "All-Season tread compound delivers..." later is redundant.
         * tireType still gets its own sentence since it speaks to a different
         * angle (structural purpose, e.g. towing/hauling) rather than
         * restating season/terrain.
         *
         * Detail-sentence order is shuffled and the mileage-warranty/closing-
         * line phrasing is picked from a small pool -- both seeded by
         * fields.sku (see hashString()/seededShuffle()) -- so a batch of items
         * doesn't read as the same template with different numbers swapped
         * in. Seeding by sku rather than group means sibling sizes of the
         * same model line still vary from each other.
         * @param {Object} fields
         * @param {string} fields.sku - used only to seed the deterministic
         *   variety picks below, not part of the description itself.
         * @param {string} fields.group - model name (e.g. "Ragnarok GTS"),
         *   distinct from productName's full title -- preferred as the
         *   description's subject when present.
         * @returns {string}
         */
        function buildShortDescription(fields) {
            const seed = hashString(fields.sku || fields.group || fields.productName || fields.brand);

            // Only the PRIMARY tireType/tireTerrain (index 0) is used -- an item
            // can legitimately carry more than one tag (e.g. TIRE_TYPE_FIELD_MAPPING's
            // 'Off-Road / All Terrain' raw value maps to BOTH 'Off-Road' and
            // 'All-Terrain'), but each is written as a self-contained claim, so
            // more than one in prose reads as contradictory rather than descriptive.
            // The full array is still submitted to Walmart unchanged -- this only
            // limits how many tags become prose.
            const primaryTireType = fields.tireType[0];
            const primaryTireTerrain = fields.tireTerrain[0];

            const seasonAdj = fields.tireSeason ? fields.tireSeason.toLowerCase() : '';
            const terrainAdj = primaryTireTerrain ? primaryTireTerrain.toLowerCase() : '';
            const descriptors = [seasonAdj, terrainAdj].filter(Boolean).join(', ');
            const tireNoun = descriptors ? `${descriptors} tire` : 'tire';

            const vehicleText = fields.vehicleType.length
                ? joinWithAnd(fields.vehicleType.map((v) => VEHICLE_TYPE_PLURAL[v] || v.toLowerCase()))
                : '';
            const useClause = vehicleText ? ` that's designed for use on ${vehicleText}` : '';

            // group (model name, e.g. "Ragnarok GTS") is preferred over productName
            // (salesdescription's full title, e.g. "Venom Power 245/35ZR20 95W XL
            // Ragnarok GTS") -- a model name reads naturally as a sentence subject
            // the way a full title doesn't. No trailing "tire" on the brandSize/bare
            // fallbacks -- tireNoun below already ends in "tire" ("...is a/an [x]
            // tire"), so appending it here too would read as "This tire is a tire."
            const brandSize = [fields.brand, fields.tireSize].filter(Boolean).join(' ');
            const subject = fields.group
                ? (fields.brand ? `The ${fields.group} from ${fields.brand}` : `The ${fields.group}`)
                : (fields.productName || (brandSize ? `The ${brandSize}` : 'This'));

            const introSentence = `${subject} is ${article(descriptors || 'tire')} ${tireNoun}${useClause}.`;

            // Model is already named in the intro sentence, so these detail
            // sentences use "It"/"It's" like normal prose, not the model name
            // again every time (real tire-retailer copy names the model up
            // front, then once more as a closing flourish at the very end --
            // see below -- but not on every fact sentence in between).
            // Collected into a pool and shuffled below rather than appended
            // in this fixed order.
            //
            // tireType/tireSpeedRating/tireLoadIndex/isRunFlat each use their
            // SHORT_DESC_*/*_SHORT_DESC_SENTENCES phrasing here, NOT the
            // KEY_FEATURES_BY_*/RUN_FLAT_KEY_FEATURE text -- buildKeyFeatures()
            // already turns those same facts into keyFeatures bullets, and this
            // item's keyFeatures + shortDescription are shown to a reviewer
            // together, so reusing that exact wording here would read as the same
            // sentence twice. See the comment above SHORT_DESC_TIRE_TYPE_SENTENCES.
            const detailSentences = [];
            if (SHORT_DESC_TIRE_TYPE_SENTENCES[primaryTireType]) detailSentences.push(SHORT_DESC_TIRE_TYPE_SENTENCES[primaryTireType]);
            const speedRatingMph = parseSpeedRatingMph(KEY_FEATURES_BY_SPEED_RATING[fields.tireSpeedRating]);
            if (speedRatingMph) {
                const speedSentence = SPEED_RATING_SHORT_DESC_SENTENCES[(seed + 3) % SPEED_RATING_SHORT_DESC_SENTENCES.length];
                detailSentences.push(speedSentence(fields.tireSpeedRating, speedRatingMph.mph, speedRatingMph.plus));
            }
            const loadIndexLbs = parseLoadIndexLbs(KEY_FEATURES_BY_LOAD_INDEX[fields.tireLoadIndex]);
            if (loadIndexLbs) {
                const loadSentence = LOAD_INDEX_SHORT_DESC_SENTENCES[(seed + 5) % LOAD_INDEX_SHORT_DESC_SENTENCES.length];
                detailSentences.push(loadSentence(loadIndexLbs));
            }
            if (fields.isRunFlat === 'Yes') detailSentences.push(SHORT_DESC_RUN_FLAT_SENTENCE);
            if (fields.electricVehicleTire === 'Yes') detailSentences.push(SHORT_DESC_ELECTRIC_VEHICLE_SENTENCE);
            if (fields.uniformTireQualityGrade) detailSentences.push(`It carries a UTQG rating of ${fields.uniformTireQualityGrade} for treadwear, traction, and temperature resistance.`);
            if (fields.mileageWarrantyMeasure) {
                const mileageSentence = MILEAGE_WARRANTY_SENTENCES[(seed + 7) % MILEAGE_WARRANTY_SENTENCES.length];
                detailSentences.push(mileageSentence(formatNumber(fields.mileageWarrantyMeasure)));
            }

            const sentences = [introSentence, ...seededShuffle(detailSentences, seed)];

            let filler = 0;
            while (countWords(sentences.join(' ')) < 60 && filler < GENERIC_DESCRIPTION_FILLERS.length) {
                sentences.push(GENERIC_DESCRIPTION_FILLERS[filler]);
                filler++;
            }

            // Closing bookend -- names the model once more at the very end,
            // mirroring how real tire-retailer copy wraps up ("...have produced
            // the Lexani Terrain Beast incorporating the very latest
            // technology...") rather than only naming it up front.
            if (fields.group) {
                const closingSentence = CLOSING_LINE_SENTENCES[(seed + 13) % CLOSING_LINE_SENTENCES.length];
                sentences.push(closingSentence(fields.group));
            }

            return sentences.join(' ');
        }

        /** True for undefined/null/empty-string/empty-array; false for 0, false, and non-empty objects. */
        function isBlank(value) {
            if (value === undefined || value === null) return true;
            if (typeof value === 'string') return value.trim() === '';
            if (Array.isArray(value)) return value.length === 0;
            if (typeof value === 'object') return Object.keys(value).length === 0;
            return false;
        }

        /**
         * Generates a unique, checksum-valid 12-digit test UPC-A from an item's
         * internal ID -- one hardcoded value shared across a feed would submit
         * the same "product" ID for different SKUs and could trigger Walmart's
         * product-matching logic to treat them as the same item. Deterministic
         * per internal ID (padded with leading 9s to 11 digits, a prefix range
         * unlikely to collide with a real registered UPC), with a real UPC-A
         * check digit appended so it's valid, not just the right length.
         * @param {string|number} internalId
         * @returns {string} 12-digit UPC-A
         */
        function generateTestUpc(internalId) {
            const base11 = ('99999999999' + String(internalId).replace(/\D/g, '')).slice(-11);
            const digits = base11.split('').map(Number);
            let oddSum = 0;
            let evenSum = 0;
            digits.forEach((d, i) => {
                if (i % 2 === 0) oddSum += d; else evenSum += d;
            });
            const checkDigit = (10 - ((oddSum * 3 + evenSum) % 10)) % 10;
            return base11 + checkDigit;
        }

        // Fields whose NetSuite custom field definition allows multiple
        // selections. Add a column here if a future multi-select field needs it.
        const MULTISELECT_COLUMNS = new Set([
            COLUMNS.VISIBLE.TIRE_TERRAIN,
            COLUMNS.VISIBLE.TIRE_TYPE,
            COLUMNS.VISIBLE.VEHICLE_TYPE
        ]);

        function getColumnValue(values, key) {
            const raw = values[key];
            const isMulti = MULTISELECT_COLUMNS.has(key);
            if (raw === null || raw === undefined) return isMulti ? [] : '';
            if (Array.isArray(raw)) {
                const texts = raw.map((item) => (item && typeof item === 'object' ? (item.text || item.value || '') : item)).filter(Boolean);
                return isMulti ? texts : (texts[0] || '');
            }
            if (typeof raw === 'object') {
                const single = raw.text || raw.value || '';
                return isMulti ? (single ? [single] : []) : single;
            }
            return isMulti ? String(raw).split('|').map((s) => s.trim()).filter(Boolean) : raw;
        }

        /**
         * Maps a NetSuite checkbox field's value (raw boolean true/false, or
         * the "T"/"F" strings a saved search more commonly returns for
         * checkbox columns) to Walmart's "Yes"/"No" string enum -- e.g.
         * isRunFlat. Anything else (blank, or an already-correct "Yes"/"No")
         * passes through unchanged, so isBlank()/applyPlaceholders() can
         * still detect a genuinely missing value. Same helper as
         * wm_mr_tire_upload.js's mapCheckboxToYesNo().
         * @param {*} value
         * @returns {*}
         */
        function mapCheckboxToYesNo(value) {
            if (value === true || value === 'T' || value === 'true') return 'Yes';
            if (value === false || value === 'F' || value === 'false') return 'No';
            return value;
        }

        // Format depends on custitem_tire_dim_unit_type -- see
        // COLUMNS.VISIBLE.DIMENSION_UNIT_TYPE. Compared by TEXT, not internal id
        // (1/2): getColumnValue() returns a list field's display text
        // ("LT-Metric (IN)" / "P-Metrics (MM)"), not its internal id, since text
        // wins whenever both are present -- same reason tireClass is compared
        // against 'LT' (its text) rather than its internal id.
        // LT-Metric doesn't use aspect ratio (uses tireHeightMeasure instead);
        // P-Metric/the no-unit-type fallback don't use tireHeightMeasure -- so
        // each branch only requires the fields its own format actually needs.
        function buildTireSizeString(tireWidthMeasure, tireHeightMeasure, tireAspectRatio, tireDiameterMeasure, tireDimensionUnitType, tireClass) {
            if (!tireDiameterMeasure) return '';
            if (tireDimensionUnitType === 'LT-Metric (IN)') {
                if (!tireWidthMeasure || !tireHeightMeasure) return '';
                return tireClass === 'LT'
                    ? `${tireHeightMeasure}X${tireWidthMeasure}R${tireDiameterMeasure}${tireClass}`
                    : `${tireHeightMeasure}X${tireWidthMeasure}R${tireDiameterMeasure}`;
            }
            if (tireDimensionUnitType === 'P-Metrics (MM)') {
                if (!tireWidthMeasure || !tireAspectRatio) return '';
                return tireClass === 'LT'
                    ? `${tireClass}${tireWidthMeasure}/${tireAspectRatio}R${tireDiameterMeasure}`
                    : `${tireWidthMeasure}/${tireAspectRatio}R${tireDiameterMeasure}`;
            }
            if (!tireWidthMeasure || !tireAspectRatio) return '';
            return `${tireWidthMeasure}/${tireAspectRatio}R${tireDiameterMeasure}`;
        }

        function mapTireType(rawValues) {
            const tireTypeValues = [];
            const tireTerrainValues = [];
            rawValues.forEach((raw) => {
                const mapping = TIRE_TYPE_FIELD_MAPPING[raw];
                if (!mapping) return;
                const target = mapping.walmartField === 'tireTerrain' ? tireTerrainValues : tireTypeValues;
                target.push(...mapping.values);
            });
            return {
                tireType: Array.from(new Set(tireTypeValues)),
                tireTerrain: Array.from(new Set(tireTerrainValues))
            };
        }

        function mapVehicleType(rawValues) {
            const mapped = rawValues.reduce((acc, raw) => acc.concat(VEHICLE_TYPE_MAPPING[raw] || []), []);
            return Array.from(new Set(mapped));
        }

        // custitem_terrain_amani -> Walmart tireTerrain enum
        // (All-Terrain/Highway Terrain/Ice/Mud Terrain/Off-Road/Sand/Snow).
        // Raw NetSuite text doesn't reliably already match Walmart's exact
        // enum spelling ("Street" has no Walmart equivalent name at all;
        // "All Terrain" is missing Walmart's hyphen) -- mapped explicitly
        // rather than passed through, same reasoning as VEHICLE_TYPE_MAPPING
        // above. Same mapping as wm_mr_tire_upload.js's TIRE_TERRAIN_MAPPING.
        const TIRE_TERRAIN_MAPPING = {
            'Street': 'Highway Terrain',
            'Highway': 'Highway Terrain',
            'Highway Terrain': 'Highway Terrain',
            'Off-Road': 'Off-Road',
            'Off Road': 'Off-Road',
            'All Terrain': 'All-Terrain',
            'All-Terrain': 'All-Terrain',
            'Mud Terrain': 'Mud Terrain',
            'Mud': 'Mud Terrain',
            'Ice': 'Ice',
            'Sand': 'Sand',
            'Snow': 'Snow'
        };

        /**
         * Maps raw custitem_terrain_amani values to Walmart's tireTerrain
         * enum (see TIRE_TERRAIN_MAPPING above), dropping anything unmapped
         * rather than guessing or passing raw NetSuite text straight through.
         * @param {string[]} rawValues
         * @returns {string[]}
         */
        function mapTireTerrain(rawValues) {
            const mapped = rawValues.reduce((acc, raw) => {
                const walmartValue = TIRE_TERRAIN_MAPPING[raw];
                return walmartValue ? acc.concat(walmartValue) : acc;
            }, []);
            return Array.from(new Set(mapped));
        }

        // ISO 3166-1 alpha-2 code -> Walmart's exact country_of_origin_substantial_
        // transformation enum.
        const COUNTRY_CODE_TO_NAME = {
            AF: 'Afghanistan', AX: 'Aland Islands', AL: 'Albania', DZ: 'Algeria',
            AS: 'American Samoa', AD: 'Andorra', AO: 'Angola', AI: 'Anguilla',
            AQ: 'Antarctica', AG: 'Antigua and Barbuda', AR: 'Argentina', AM: 'Armenia',
            AW: 'Aruba', AU: 'Australia', AT: 'Austria', AZ: 'Azerbaijan',
            BS: 'Bahamas', BH: 'Bahrain', BD: 'Bangladesh', BB: 'Barbados',
            BY: 'Belarus', BE: 'Belgium', BZ: 'Belize', BJ: 'Benin',
            BM: 'Bermuda', BT: 'Bhutan', BO: 'Bolivia', BQ: 'Bonaire',
            BA: 'Bosnia and Herzegovina', BW: 'Botswana', BV: 'Bouvet Island', BR: 'Brazil',
            IO: 'British Indian Ocean Territory', BN: 'Brunei Darussalam', BG: 'Bulgaria', BF: 'Burkina Faso',
            BI: 'Burundi', KH: 'Cambodia', CM: 'Cameroon', CA: 'Canada',
            CV: 'Cape Verde', KY: 'Cayman Islands', CF: 'Central African Republic', TD: 'Chad',
            CL: 'Chile', CN: 'China', CX: 'Christmas Island', CC: 'Cocos (Keeling) Islands',
            CO: 'Colombia', KM: 'Comoros', CK: 'Cook Islands', CR: 'Costa Rica',
            CI: 'Cote d Ivoire', HR: 'Croatia', CU: 'Cuba', CW: 'Curacao',
            CY: 'Cyprus', CZ: 'Czech Republic', CD: 'Democratic Republic of the Congo', DK: 'Denmark',
            DJ: 'Djibouti', DM: 'Dominica', DO: 'Dominican Republic', EC: 'Ecuador',
            EG: 'Egypt', SV: 'El Salvador', GQ: 'Equatorial Guinea', ER: 'Eritrea',
            EE: 'Estonia', SZ: 'Eswatini', ET: 'Ethiopia', FK: 'Falkland Islands (Malvinas)',
            FO: 'Faroe Islands', FJ: 'Fiji', FI: 'Finland', FR: 'France',
            GF: 'French Guiana', PF: 'French Polynesia', TF: 'French Southern Territories', GA: 'Gabon',
            GM: 'Gambia', GE: 'Georgia', DE: 'Germany', GH: 'Ghana',
            GI: 'Gibraltar', GR: 'Greece', GL: 'Greenland', GD: 'Grenada',
            GP: 'Guadeloupe', GU: 'Guam', GT: 'Guatemala', GG: 'Guernsey',
            GN: 'Guinea', GW: 'Guinea-Bissau', GY: 'Guyana', HT: 'Haiti',
            HM: 'Heard Island & McDonald Isl', HN: 'Honduras', HK: 'Hong Kong', HU: 'Hungary',
            IS: 'Iceland', IN: 'India', ID: 'Indonesia', IR: 'Iran',
            IQ: 'Iraq', IE: 'Ireland', IM: 'Isle of Man', IL: 'Israel',
            IT: 'Italy', JM: 'Jamaica', JP: 'Japan', JE: 'Jersey',
            JO: 'Jordan', KZ: 'Kazakhstan', KE: 'Kenya', KI: 'Kiribati',
            KP: 'Korea, North', KR: 'Korea, South', XK: 'Kosovo', KW: 'Kuwait',
            KG: 'Kyrgyzstan', LA: 'Laos', LV: 'Latvia', LB: 'Lebanon',
            LS: 'Lesotho', LR: 'Liberia', LY: 'Libyan Arab Jamahiriya', LI: 'Liechtenstein',
            LT: 'Lithuania', LU: 'Luxembourg', MO: 'Macau', MK: 'Macedonia',
            MG: 'Madagascar', MW: 'Malawi', MY: 'Malaysia', MV: 'Maldives',
            ML: 'Mali', MT: 'Malta', MH: 'Marshall Islands', MQ: 'Martinique',
            MR: 'Mauritania', MU: 'Mauritius', YT: 'Mayotte', MX: 'Mexico',
            FM: 'Micronesia', MD: 'Moldova', MC: 'Monaco', MN: 'Mongolia',
            ME: 'Montenegro', MS: 'Montserrat', MA: 'Morocco', MZ: 'Mozambique',
            MM: 'Myanmar', NA: 'Namibia', NR: 'Nauru', NP: 'Nepal',
            NL: 'Netherlands', NC: 'New Caledonia', NZ: 'New Zealand', NI: 'Nicaragua',
            NE: 'Niger', NG: 'Nigeria', NU: 'Niue', NF: 'Norfolk Island',
            MP: 'Northern Mariana Islands', NO: 'Norway', OM: 'Oman', PK: 'Pakistan',
            PW: 'Palau', PS: 'Palestine', PA: 'Panama', PG: 'Papua New Guinea',
            PY: 'Paraguay', PE: 'Peru', PH: 'Philippines', PN: 'Pitcairn',
            PL: 'Poland', PT: 'Portugal', PR: 'Puerto Rico', QA: 'Qatar',
            CG: 'Republic of the Congo', RE: 'Reunion', RO: 'Romania', RU: 'Russian Federation',
            RW: 'Rwanda', BL: 'Saint Barthelemy', SH: 'Saint Helena', KN: 'Saint Kitts And Nevis',
            LC: 'Saint Lucia', SX: 'Saint Maarten', MF: 'Saint Martin', PM: 'Saint Pierre And Miquelon',
            VC: 'Saint Vincent & the Grenadines', WS: 'Samoa', SM: 'San Marino', ST: 'Sao Tome and Principe',
            SA: 'Saudi Arabia', SN: 'Senegal', RS: 'Serbia', SC: 'Seychelles',
            SL: 'Sierra Leone', SG: 'Singapore', SK: 'Slovakia', SI: 'Slovenia',
            SB: 'Solomon Islands', SO: 'Somalia', ZA: 'South Africa', GS: 'South Georgia/So Sandwich Isl',
            SS: 'South Sudan', ES: 'Spain', LK: 'Sri Lanka', SD: 'Sudan',
            SR: 'Suriname', SJ: 'Svalbard and Jan Mayen', SE: 'Sweden', CH: 'Switzerland',
            SY: 'Syrian Arab Republic', TW: 'Taiwan', TJ: 'Tajikistan', TZ: 'Tanzania',
            TH: 'Thailand', TL: 'Timor-Leste', TG: 'Togo', TK: 'Tokelau',
            TO: 'Tonga', TT: 'Trinidad and Tobago', TN: 'Tunisia', TR: 'Turkey',
            TM: 'Turkmenistan', TC: 'Turks and Caicos Islands', TV: 'Tuvalu', UG: 'Uganda',
            UA: 'Ukraine', AE: 'United Arab Emirates', GB: 'United Kingdom', US: 'United States',
            UY: 'Uruguay', UM: 'US Minor Outlying Islands', UZ: 'Uzbekistan', VU: 'Vanuatu',
            VA: 'Vatican City State', VE: 'Venezuela', VN: 'Viet Nam', VG: 'Virgin Islands (British)',
            VI: 'Virgin Islands (U.S.)', WF: 'Wallis and Futuna Islands', EH: 'Western Sahara', YE: 'Yemen',
            ZM: 'Zambia', ZW: 'Zimbabwe'
        };

        /**
         * Translates countryofmanufacture's raw 2-letter code into Walmart's exact
         * country_of_origin_substantial_transformation enum spelling (see
         * COUNTRY_CODE_TO_NAME above). Case-insensitive since NetSuite's raw value
         * has been seen both upper- and lower-case; returns undefined (not a
         * placeholder) for anything blank or not in the map, so the caller decides
         * the fallback rather than this function guessing one.
         * @param {string} rawCode
         * @returns {string|undefined}
         */
        function mapCountryOfOrigin(rawCode) {
            if (!rawCode) return undefined;
            return COUNTRY_CODE_TO_NAME[String(rawCode).trim().toUpperCase()];
        }

        /**
         * Extracts just the leading numeric portion of a raw UTQG value
         * (e.g. "500AA" -> "500", "300 AB" -> "300", "320 A A" -> "320") for
         * tireTreadwearRating.
         * @param {string} rawUtqg
         * @returns {string}
         */
        function extractTreadwearNumber(rawUtqg) {
            if (!rawUtqg) return '';
            const match = String(rawUtqg).trim().match(/^\d+/);
            return match ? match[0] : '';
        }

        /**
         * Fills any blank field on orderable/tiresVisible with its PLACEHOLDERS
         * entry, INCLUDING conditionally-required fields whose trigger fires
         * once tireType/vehicleType placeholders (if needed) are applied.
         * @returns {string[]} names of fields that got a placeholder value
         */
        function applyPlaceholders(orderable, tiresVisible) {
            const applied = [];
            function fill(obj, field, value) {
                if (isBlank(obj[field])) {
                    obj[field] = value;
                    applied.push(field);
                }
            }

            // productIdentifiers / country_of_origin_substantial_transformation
            // are no longer conditionally filled here -- buildTestWalmartItem()
            // now hardcodes both unconditionally (see there for why), so they're
            // never blank by the time applyPlaceholders() runs.
            if (!orderable.price) { orderable.price = 9.99; applied.push('price'); }
            if (!orderable.ShippingWeight) { orderable.ShippingWeight = 20; applied.push('ShippingWeight'); }

            // shortDescription isn't in this list -- buildTestWalmartItem() generates
            // it via buildShortDescription() AFTER this function returns, from
            // tiresVisible's final (placeholder-filled) attribute values.
            ['productName', 'brand', 'manufacturer', 'manufacturerPartNumber',
                'mainImageUrl', 'tireSize', 'tireSeason', 'tireTerrain',
                'tireType', 'vehicleType', 'isRunFlat', 'electric_vehicle_tire', 'warrantyURL',
                'prop65WarningText'
            ].forEach((field) => fill(tiresVisible, field, PLACEHOLDERS[field]));

            // productSecondaryImageURL needs its own handling, not the generic
            // fill() above -- Walmart's schema requires minItems: 2, but fill()
            // only replaces the whole array when it's completely empty. An item
            // with exactly ONE real secondary image would pass isBlank() (a
            // non-empty array isn't blank) and stay at length 1, failing schema
            // validation. Padded up to 2 with placeholders instead, keeping any
            // real image(s) already present rather than discarding them.
            if (tiresVisible.productSecondaryImageURL.length === 0) {
                tiresVisible.productSecondaryImageURL = PLACEHOLDERS.productSecondaryImageURL.slice();
                applied.push('productSecondaryImageURL');
            } else if (tiresVisible.productSecondaryImageURL.length < 2) {
                const needed = 2 - tiresVisible.productSecondaryImageURL.length;
                tiresVisible.productSecondaryImageURL = tiresVisible.productSecondaryImageURL.concat(
                    PLACEHOLDERS.productSecondaryImageURL.slice(0, needed)
                );
                applied.push('productSecondaryImageURL');
            }

            // keyFeatures isn't filled here -- buildTestWalmartItem() generates it
            // via buildKeyFeatures() AFTER this function returns, same timing/
            // reasoning as shortDescription below (it needs tireSpeedRating/
            // tireLoadIndex, which are only conditionally placeholder-filled later
            // in this function -- see requiresLoadSpeedConstruction below).

            if (isBlank(tiresVisible.assembledProductWeight)) {
                tiresVisible.assembledProductWeight = { unit: 'lb', measure: 20 };
                applied.push('assembledProductWeight');
            }
            if (isBlank(tiresVisible.tireWidth)) {
                tiresVisible.tireWidth = { unit: 'mm', measure: 225 };
                applied.push('tireWidth');
            }
            if (isBlank(tiresVisible.wheelDiameter)) {
                tiresVisible.wheelDiameter = { unit: 'in', measure: 18 };
                applied.push('wheelDiameter');
            }

            // Re-evaluate conditional triggers using the FINAL tireType/vehicleType
            // (real data if present, otherwise the placeholders just applied above).
            const requiresLoadSpeedConstruction = tiresVisible.tireType.some(
                (t) => TIRE_TYPES_REQUIRING_LOAD_SPEED_CONSTRUCTION.includes(t)
            );
            const requiresUniformTireQualityGrade = tiresVisible.tireType.some(
                (t) => TIRE_TYPES_REQUIRING_UNIFORM_QUALITY_GRADE.includes(t)
            );
            const requiresTireTreadwearRating = tiresVisible.vehicleType.some(
                (t) => VEHICLE_TYPES_REQUIRING_TREADWEAR_RATING.includes(t)
            );
            const requiresMileageWarranty = tiresVisible.vehicleType.some(
                (t) => VEHICLE_TYPES_REQUIRING_MILEAGE_WARRANTY.includes(t)
            );

            if (requiresLoadSpeedConstruction) {
                fill(tiresVisible, 'tireAspectRatio', PLACEHOLDERS.tireAspectRatio);
                fill(tiresVisible, 'tireLoadIndex', PLACEHOLDERS.tireLoadIndex);
                fill(tiresVisible, 'tireSpeedRating', PLACEHOLDERS.tireSpeedRating);
            }
            if (requiresUniformTireQualityGrade) {
                fill(tiresVisible, 'uniformTireQualityGrade', PLACEHOLDERS.uniformTireQualityGrade);
            }
            if (requiresTireTreadwearRating) {
                fill(tiresVisible, 'tireTreadwearRating', PLACEHOLDERS.tireTreadwearRating);
            }
            if (requiresMileageWarranty && isBlank(tiresVisible.mileageWarranty)) {
                tiresVisible.mileageWarranty = { unit: 'miles', measure: 50000 };
                applied.push('mileageWarranty');
            }

            return applied;
        }

        /**
         * Same field sourcing/translation as wm_mr_tire_upload.js's
         * buildWalmartItem() / wm_sl_test_upload.js's buildTestWalmartItem(),
         * then placeholder-fills anything still blank. keyFeatures/shortDescription
         * are synthesized separately from the FINAL values -- see
         * buildKeyFeatures()/buildShortDescription() calls below.
         * @param {Object} values - result.getAllValues() for the chosen item
         * @param {string} internalId
         */
        function buildTestWalmartItem(values, internalId) {
            const sku = getColumnValue(values, COLUMNS.ORDERABLE.SKU) || `TEST-SKU-${internalId}`;
            const price = parseFloat(getColumnValue(values, COLUMNS.ORDERABLE.PRICE)) || 0;
            const shippingWeight = parseFloat(getColumnValue(values, COLUMNS.ORDERABLE.SHIPPING_WEIGHT)) || 0;

            const brand = getColumnValue(values, COLUMNS.VISIBLE.BRAND);
            const manufacturer = getColumnValue(values, COLUMNS.VISIBLE.MANUFACTURER) || brand;
            // Model name only (e.g. "Ragnarok GTS"), as opposed to
            // productName/salesdescription's full title (e.g. "Venom Power
            // 245/35ZR20 95W XL Ragnarok GTS") -- used as the shortDescription's
            // subject instead, since a model name reads naturally in prose
            // ("The Ragnarok GTS from Venom Power is...") where the full
            // title doesn't. See buildShortDescription().
            const group = getColumnValue(values, COLUMNS.VISIBLE.GROUP);
            const assembledWeight = parseFloat(getColumnValue(values, COLUMNS.VISIBLE.ASSEMBLED_PRODUCT_WEIGHT)) || 0;

            const tireWidthMeasure = parseFloat(getColumnValue(values, COLUMNS.VISIBLE.TIRE_WIDTH)) || 0;
            const tireDiameterMeasure = parseFloat(getColumnValue(values, COLUMNS.VISIBLE.TIRE_DIAMETER)) || 0;
            const tireAspectRatio = getColumnValue(values, COLUMNS.VISIBLE.ASPECT_RATIO);
            const tireHeightMeasure = parseFloat(getColumnValue(values, COLUMNS.VISIBLE.TIRE_HEIGHT)) || 0;
            const tireDimensionUnitType = getColumnValue(values, COLUMNS.VISIBLE.DIMENSION_UNIT_TYPE);
            const tireClass = getColumnValue(values, COLUMNS.VISIBLE.TIRE_CLASS);
            const tireSize = getColumnValue(values, COLUMNS.VISIBLE.TIRE_SIZE)
                || buildTireSizeString(tireWidthMeasure, tireHeightMeasure, tireAspectRatio, tireDiameterMeasure, tireDimensionUnitType, tireClass);

            const tireLoadIndex = getColumnValue(values, COLUMNS.VISIBLE.TIRE_LOAD_INDEX);
            const tireSpeedRating = getColumnValue(values, COLUMNS.VISIBLE.TIRE_SPEED_RATING);
            const tireSeason = getColumnValue(values, COLUMNS.VISIBLE.TIRE_SEASON);
            const isRunFlat = mapCheckboxToYesNo(getColumnValue(values, COLUMNS.VISIBLE.IS_RUN_FLAT));

            // All tires are assumed to have Radial construction for now.
            const constructionType = 'Radial';
            const uniformTireQualityGrade = getColumnValue(values, COLUMNS.VISIBLE.UNIFORM_TIRE_QUALITY_GRADE);
            const tireTreadwearRating = extractTreadwearNumber(getColumnValue(values, COLUMNS.VISIBLE.TIRE_TREADWEAR_RATING));
            const mileageWarrantyMeasure = parseInt(getColumnValue(values, COLUMNS.VISIBLE.MILEAGE_WARRANTY), 10) || 0;
            const warrantyUrl = getColumnValue(values, COLUMNS.VISIBLE.WARRANTY_URL);

            const secondaryImages = [
                getColumnValue(values, COLUMNS.VISIBLE.SECONDARY_IMAGE_FACE),
                getColumnValue(values, COLUMNS.VISIBLE.SECONDARY_IMAGE_SIDE)
            ].filter(Boolean);
            const rawTireTerrain = getColumnValue(values, COLUMNS.VISIBLE.TIRE_TERRAIN);
            const rawTireType = getColumnValue(values, COLUMNS.VISIBLE.TIRE_TYPE);
            const rawVehicleType = getColumnValue(values, COLUMNS.VISIBLE.VEHICLE_TYPE);

            const { tireType: tireTypeFromMapping, tireTerrain: tireTerrainFromTireType } = mapTireType(rawTireType);
            const tireTypeFromClass = TIRE_CLASS_TO_TIRE_TYPE[tireClass];
            const tireType = Array.from(new Set(tireTypeFromClass ? [...tireTypeFromMapping, tireTypeFromClass] : tireTypeFromMapping));
            const tireTerrain = Array.from(new Set([...mapTireTerrain(rawTireTerrain), ...tireTerrainFromTireType]));
            const vehicleType = mapVehicleType(rawVehicleType);

            const tiresVisible = {
                productName: getColumnValue(values, COLUMNS.VISIBLE.PRODUCT_NAME),
                brand,
                condition: 'New',
                // Generated below (see buildShortDescription() call after
                // applyPlaceholders()) rather than sourced from
                // salesdescription or a fixed placeholder -- this is where
                // that generated text gets reviewed against real sandbox
                // items before it's ported to wm_mr_tire_upload.js.
                shortDescription: undefined,
                keyFeatures: undefined, // generated below (see buildKeyFeatures() call after applyPlaceholders())
                mainImageUrl: getColumnValue(values, COLUMNS.VISIBLE.MAIN_IMAGE_URL),
                productSecondaryImageURL: secondaryImages,
                count: 1,
                multipackQuantity: 1,
                assembledProductWeight: assembledWeight ? { unit: 'lb', measure: assembledWeight } : undefined,
                manufacturer,
                manufacturerPartNumber: getColumnValue(values, COLUMNS.VISIBLE.MANUFACTURER_PART_NUMBER),
                netContent: { productNetContentUnit: 'Each', productNetContentMeasure: 1 },
                tireSize,
                tireWidth: tireWidthMeasure ? { unit: 'mm', measure: tireWidthMeasure } : undefined,
                wheelDiameter: tireDiameterMeasure ? { unit: 'in', measure: tireDiameterMeasure } : undefined,
                tireAspectRatio: tireAspectRatio || undefined,
                tireLoadIndex,
                tireSpeedRating,
                constructionType,
                uniformTireQualityGrade: uniformTireQualityGrade || undefined,
                tireTreadwearRating: tireTreadwearRating || undefined,
                mileageWarranty: mileageWarrantyMeasure ? { unit: 'miles', measure: mileageWarrantyMeasure } : undefined,
                tireTerrain,
                tireType,
                vehicleType,
                tireSeason,
                isRunFlat,
                electric_vehicle_tire: mapCheckboxToYesNo(getColumnValue(values, COLUMNS.VISIBLE.ELECTRIC_VEHICLE_TIRE)),
                flotation_tire: 'No',
                isProp65WarningRequired: 'Yes',
                prop65WarningText: undefined,
                has_written_warranty: 'Yes - Warranty URL',
                warrantyURL: warrantyUrl || undefined
            };

            const orderable = {
                sku,
                // Generated (see generateTestUpc()) rather than sourced from
                // custitemtire_upc/upccode -- real UPC/GTIN values in NetSuite
                // aren't reliably valid for the productIdType they get labeled
                // with (e.g. a 13-digit EAN-style code labeled "UPC", which is a
                // 12-digit format), which is a per-item NetSuite data-quality
                // problem, not a pipeline problem. A unique-per-item generated
                // test value keeps this tool testing the pipeline only, same
                // PLACEHOLDERS philosophy as the rest of this
                // file (see file header / PLACEHOLDERS above).
                productIdentifiers: {
                    productIdType: 'UPC',
                    productId: generateTestUpc(internalId)
                },
                ShippingWeight: shippingWeight || undefined,
                price,
                // countryofmanufacture holds a 2-letter ISO code (e.g. "US"), not a
                // valid enum entry on its own -- translated via mapCountryOfOrigin()/
                // COUNTRY_CODE_TO_NAME above into Walmart's exact enum spelling,
                // falling back to "United States" for any blank/unmapped code rather
                // than sourcing a fake test value like productIdentifiers above.
                country_of_origin_substantial_transformation:
                    mapCountryOfOrigin(getColumnValue(values, COLUMNS.ORDERABLE.COUNTRY_OF_ORIGIN)) || 'United States'
            };

            const placeholdersApplied = applyPlaceholders(orderable, tiresVisible);

            // Generated from tiresVisible's FINAL attribute values -- i.e.
            // after any blank tireType/vehicleType/etc. were placeholder-
            // filled above -- so the description matches what's actually
            // being submitted for this item, not just its raw NetSuite data.
            tiresVisible.shortDescription = buildShortDescription({
                sku,
                group,
                productName: tiresVisible.productName,
                brand: tiresVisible.brand,
                tireSize: tiresVisible.tireSize,
                tireType: tiresVisible.tireType,
                tireTerrain: tiresVisible.tireTerrain,
                vehicleType: tiresVisible.vehicleType,
                tireSpeedRating: tiresVisible.tireSpeedRating,
                tireLoadIndex: tiresVisible.tireLoadIndex,
                tireSeason: tiresVisible.tireSeason,
                isRunFlat: tiresVisible.isRunFlat,
                electricVehicleTire: tiresVisible.electric_vehicle_tire,
                uniformTireQualityGrade: tiresVisible.uniformTireQualityGrade,
                mileageWarrantyMeasure: tiresVisible.mileageWarranty ? tiresVisible.mileageWarranty.measure : 0
            });

            // Same FINAL-values timing/reasoning as shortDescription above.
            tiresVisible.keyFeatures = buildKeyFeatures({
                tireType: tiresVisible.tireType,
                tireTerrain: tiresVisible.tireTerrain,
                tireSpeedRating: tiresVisible.tireSpeedRating,
                tireLoadIndex: tiresVisible.tireLoadIndex,
                tireSeason: tiresVisible.tireSeason,
                isRunFlat: tiresVisible.isRunFlat,
                electricVehicleTire: tiresVisible.electric_vehicle_tire
            });

            return { orderable, tiresVisible, placeholdersApplied };
        }

        function getScriptParams() {
            const script = runtime.getCurrentScript();
            return {
                clientId: script.getParameter({ name: 'custscript_wal_multi_test_client_id' }),
                clientSecret: script.getParameter({ name: 'custscript_wal_multi_test_client_secret' }),
                savedSearchId: script.getParameter({ name: 'custscript_wal_multi_test_saved_search' })
            };
        }

        /**
         * JSON.parse that logs the raw body before throwing, so a non-JSON
         * response (HTML error page, empty body, etc.) shows up in the
         * execution log instead of just an opaque "Unexpected token" message.
         */
        function safeJsonParse(body, correlationId, context) {
            try {
                return JSON.parse(body);
            } catch (e) {
                log.error({
                    title: `Failed to parse Walmart response as JSON (${context}, correlationId=${correlationId})`,
                    details: body
                });
                throw new Error(`Walmart ${context} response was not valid JSON (correlationId=${correlationId}): ${body}`);
            }
        }

        /** Logs code/headers/body for every Walmart call so nothing is left only on-screen or silently dropped. */
        function logHttpResponse(title, response, correlationId) {
            log[response.code === 200 ? 'audit' : 'error']({
                title: `${title} (correlationId=${correlationId})`,
                details: JSON.stringify({ code: response.code, headers: response.headers, body: response.body })
            });
        }

        function getAccessToken(params) {
            const { clientId, clientSecret, correlationId } = params;
            const basicAuth = encode.convert({
                string: `${clientId}:${clientSecret}`,
                inputEncoding: encode.Encoding.UTF_8,
                outputEncoding: encode.Encoding.BASE_64
            });
            const response = https.post({
                url: `${BASE_URL}/v3/token`,
                body: 'grant_type=client_credentials',
                headers: {
                    'Authorization': `Basic ${basicAuth}`,
                    'Content-Type': 'application/x-www-form-urlencoded',
                    'Accept': 'application/json',
                    'WM_QOS.CORRELATION_ID': correlationId,
                    'WM_SVC.NAME': 'Walmart Marketplace'
                }
            });
            logHttpResponse('Walmart token request', response, correlationId);
            if (response.code !== 200) {
                throw new Error(`Walmart token request failed (${response.code}, correlationId=${correlationId}): ${response.body}`);
            }
            const parsed = safeJsonParse(response.body, correlationId, 'token');
            if (!parsed.access_token) {
                throw new Error(`Walmart token response missing access_token (correlationId=${correlationId}): ${response.body}`);
            }
            return parsed.access_token;
        }

        /**
         * Builds a multipart/form-data body by hand -- N/https has no native
         * multipart helper. Same approach as wm_sl_test_upload.js.
         */
        function buildMultipartBody(boundary, fileContent, filename) {
            const CRLF = '\r\n';
            return `--${boundary}${CRLF}`
                + `Content-Disposition: form-data; name="file"; filename="${filename}"${CRLF}`
                + `Content-Type: application/json${CRLF}${CRLF}`
                + `${fileContent}${CRLF}`
                + `--${boundary}--${CRLF}`;
        }

        function submitItemFeed(params) {
            const { accessToken, feedJson, correlationId } = params;
            const boundary = `----WalmartFeedBoundary${random.generateUUID().replace(/-/g, '')}`;
            const multipartBody = buildMultipartBody(boundary, feedJson, 'feed.json');
            const requestUrl = `${BASE_URL}/v3/feeds?feedType=${FEED_TYPE}`;
            const requestHeaders = {
                'Authorization': `Bearer ${accessToken}`,
                'WM_SEC.ACCESS_TOKEN': accessToken,
                'WM_QOS.CORRELATION_ID': correlationId,
                'WM_SVC.NAME': 'Walmart Marketplace',
                'Accept': 'application/json',
                'Content-Type': `multipart/form-data; boundary=${boundary}`
            };

            // Logs exactly what this script BUILT and asked N/https to send --
            // logHttpResponse() below only shows what Walmart sent BACK, which
            // says nothing about whether NetSuite's http layer altered the body
            // (e.g. re-flowing \r\n line endings) before it left NetSuite. Redacts
            // the access token from the logged headers (kept in the real request)
            // since this log is otherwise safe to paste into a support ticket.
            // bodyLength is the JS string's .length (UTF-16 code units, not wire
            // bytes) -- close enough to sanity-check for accidental truncation,
            // not a substitute for a real byte count.
            //
            // Metadata and body are logged SEPARATELY, and the body is chunked --
            // a single log.audit() "details" entry silently truncates around
            // NetSuite's execution log size limit (observed firsthand: a ~4.2KB
            // body wrapped in JSON.stringify(), which also doubles every \r\n into
            // \\r\\n, got cut off mid-JSON). Logging the RAW body text (no
            // JSON.stringify escaping) in ~3000-character chunks keeps each entry
            // well under that limit and avoids the escaping overhead entirely --
            // concatenate the chunks in order to reconstruct the exact body.
            log.audit({
                title: `Walmart TEST-MULTI feed submission REQUEST metadata (correlationId=${correlationId})`,
                details: JSON.stringify({
                    url: requestUrl,
                    headers: { ...requestHeaders, 'Authorization': '[redacted]', 'WM_SEC.ACCESS_TOKEN': '[redacted]' },
                    boundary,
                    bodyLength: multipartBody.length
                })
            });
            const BODY_LOG_CHUNK_SIZE = 3000;
            const bodyChunkCount = Math.ceil(multipartBody.length / BODY_LOG_CHUNK_SIZE) || 1;
            for (let i = 0; i < bodyChunkCount; i++) {
                log.audit({
                    title: `Walmart TEST-MULTI feed submission REQUEST body part ${i + 1} of ${bodyChunkCount} (correlationId=${correlationId})`,
                    details: multipartBody.substring(i * BODY_LOG_CHUNK_SIZE, (i + 1) * BODY_LOG_CHUNK_SIZE)
                });
            }

            const response = https.post({
                url: requestUrl,
                body: multipartBody,
                headers: requestHeaders
            });
            logHttpResponse('Walmart TEST-MULTI feed submission response', response, correlationId);
            if (response.code !== 200) {
                throw new Error(`Walmart feed submission failed (${response.code}, correlationId=${correlationId}): ${response.body}`);
            }
            const parsed = safeJsonParse(response.body, correlationId, 'feed submission');
            if (!parsed.feedId) {
                throw new Error(`Walmart feed submission response missing feedId (correlationId=${correlationId}): ${response.body}`);
            }
            log.audit({ title: 'Walmart TEST-MULTI feed submitted', details: `feedId=${parsed.feedId}, correlationId=${correlationId}` });
            return parsed.feedId;
        }

        /** Same tracking write as wm_sl_test_upload.js's recordTestFeedSubmission(), but for N items in one feed. */
        function recordTestFeedSubmission(params) {
            const { feedId, details, correlationId, skus } = params;
            try {
                const rec = record.create({ type: FEED_RECORD.TYPE, isDynamic: false });
                rec.setValue({ fieldId: 'name', value: `TEST-MULTI-${feedId}` });
                rec.setValue({ fieldId: FEED_RECORD.FIELDS.FEED_ID, value: feedId });
                rec.setValue({ fieldId: FEED_RECORD.FIELDS.STATUS, value: 'RECEIVED' });
                rec.setValue({ fieldId: FEED_RECORD.FIELDS.ENVIRONMENT, value: 'SANDBOX' });
                rec.setValue({ fieldId: FEED_RECORD.FIELDS.ITEM_COUNT, value: skus.length });
                rec.setValue({ fieldId: FEED_RECORD.FIELDS.SUBMITTED_DATE, value: new Date() });
                rec.setValue({ fieldId: FEED_RECORD.FIELDS.BUCKET, value: 'MANUAL-TEST-MULTI' });
                rec.setValue({ fieldId: FEED_RECORD.FIELDS.DETAILS, value: details });
                rec.setValue({ fieldId: FEED_RECORD.FIELDS.CORRELATION_ID, value: correlationId });
                rec.setValue({ fieldId: FEED_RECORD.FIELDS.FEED_TYPE, value: FEED_TYPE });
                rec.setValue({ fieldId: FEED_RECORD.FIELDS.ITEM_TYPE, value: WALMART_ITEM_TYPE });
                rec.setValue({ fieldId: FEED_RECORD.FIELDS.SKUS, value: skus.join('|') });
                return rec.save();
            } catch (e) {
                log.error({ title: `Failed to record TEST-MULTI feed submission (feedId=${feedId})`, details: e });
                return null;
            }
        }

        /** One fresh filtered search per lookup -- mirrors wm_sl_test_upload.js's findItem(), called once per line. */
        function findItemByLookup(savedSearchId, lookup) {
            const loadedSearch = search.load({ id: savedSearchId });
            const isNumeric = /^\d+$/.test(lookup.trim());
            loadedSearch.filters.push(search.createFilter({
                name: isNumeric ? 'internalid' : 'itemid',
                operator: isNumeric ? search.Operator.ANYOF : search.Operator.IS,
                values: [lookup.trim()]
            }));
            const results = loadedSearch.run().getRange({ start: 0, end: 1 });
            return results.length ? results[0] : null;
        }

        function buildForm(params) {
            const form = serverWidget.createForm({ title: `Walmart Tire Upload - Multi-Item Test (up to ${MAX_ITEMS}, SANDBOX only)` });

            const lookupField = form.addField({
                id: 'custpage_item_lookups',
                type: serverWidget.FieldType.LONGTEXT,
                label: `Item SKUs or Internal IDs (one per line, up to ${MAX_ITEMS})`
            });
            lookupField.isMandatory = true;
            if (params.lookups) lookupField.defaultValue = params.lookups;

            form.addSubmitButton({ label: 'Run Multi-Item Test Upload' });

            if (params.resultText) {
                const resultField = form.addField({
                    id: 'custpage_result',
                    type: serverWidget.FieldType.LONGTEXT,
                    label: 'Result'
                });
                resultField.defaultValue = params.resultText;
                resultField.updateDisplayType({ displayType: serverWidget.FieldDisplayType.INLINE });
            }

            return form;
        }

        const onRequest = (context) => {
            if (context.request.method !== 'POST') {
                context.response.writePage(buildForm({}));
                return;
            }

            const rawLookups = context.request.parameters.custpage_item_lookups || '';
            const lookups = rawLookups.split(/\r?\n/).map((s) => s.trim()).filter(Boolean);

            if (!lookups.length) {
                context.response.writePage(buildForm({ resultText: 'Enter at least one item SKU or internal ID.' }));
                return;
            }
            if (lookups.length > MAX_ITEMS) {
                context.response.writePage(buildForm({
                    lookups: rawLookups,
                    resultText: `Entered ${lookups.length} items -- max is ${MAX_ITEMS}. Remove ${lookups.length - MAX_ITEMS} and resubmit.`
                }));
                return;
            }

            const { clientId, clientSecret, savedSearchId } = getScriptParams();
            if (!savedSearchId) {
                context.response.writePage(buildForm({
                    lookups: rawLookups,
                    resultText: 'Missing required script parameter: custscript_wal_multi_test_saved_search'
                }));
                return;
            }

            let resultText;
            let correlationId = random.generateUUID();
            try {
                const notFound = [];
                const mpItems = [];
                const skus = [];
                const placeholdersByLookup = {};
                const descriptionsByLookup = {};

                lookups.forEach((lookup) => {
                    const result = findItemByLookup(savedSearchId, lookup);
                    if (!result) {
                        notFound.push(lookup);
                        return;
                    }
                    const values = result.getAllValues();
                    log.debug({
                        title: `Raw NetSuite values for "${lookup}" (internal id ${result.id})`,
                        details: JSON.stringify(values, null, 2)
                    });
                    const { orderable, tiresVisible, placeholdersApplied } = buildTestWalmartItem(values, result.id);
                    mpItems.push({ Orderable: orderable, Visible: { Tires: tiresVisible } });
                    skus.push(orderable.sku);
                    placeholdersByLookup[orderable.sku] = placeholdersApplied;
                    descriptionsByLookup[orderable.sku] = tiresVisible.shortDescription;
                });

                if (!mpItems.length) {
                    resultText = `None of the entered lookups matched an item: ${notFound.join(', ')}`;
                    context.response.writePage(buildForm({ lookups: rawLookups, resultText }));
                    return;
                }

                const feedPayload = {
                    MPItemFeedHeader: { businessUnit: 'WALMART_US', locale: 'en', version: FEED_SPEC_VERSION },
                    MPItem: mpItems
                };
                const feedJson = JSON.stringify(feedPayload, null, 2);

                const descriptionSummary = Object.entries(descriptionsByLookup)
                    .map(([sku, desc]) => `  ${sku} (${countWords(desc)} words):\n    ${desc}`)
                    .join('\n\n');

                if (!clientId || !clientSecret) {
                    resultText = 'Missing custscript_wal_testmulti_client_id / custscript_wal_testmulti_client_secret '
                        + `script parameters.\n\nItems that would be submitted (${mpItems.length}): ${skus.join(', ')}`
                        + `${notFound.length ? `\n\nNot found: ${notFound.join(', ')}` : ''}`
                        + `\n\nGenerated shortDescription per item:\n${descriptionSummary}\n\n`
                        + `Built feed (not submitted):\n${feedJson}`;
                    context.response.writePage(buildForm({ lookups: rawLookups, resultText }));
                    return;
                }

                const accessToken = getAccessToken({ clientId, clientSecret, correlationId });
                correlationId = random.generateUUID();
                const feedId = submitItemFeed({ accessToken, feedJson, correlationId });
                const trackingId = recordTestFeedSubmission({ feedId, details: feedJson, correlationId, skus });

                const placeholderSummary = Object.entries(placeholdersByLookup)
                    .map(([sku, fields]) => `  ${sku}: ${fields.length ? fields.join(', ') : '(none -- item had every field populated)'}`)
                    .join('\n');

                resultText = `Feed submitted to Walmart SANDBOX with ${mpItems.length} item(s). feedId=${feedId}\n\n`
                    + `correlationId: ${correlationId} (reference this if you need to ask Walmart support about this submission)\n\n`
                    + `SKUs submitted: ${skus.join(', ')}\n`
                    + `${notFound.length ? `Not found (skipped): ${notFound.join(', ')}\n` : ''}\n`
                    + `Placeholders applied per item:\n${placeholderSummary}\n\n`
                    + `Generated shortDescription per item:\n${descriptionSummary}\n\n`
                    + `Tracking record: ${trackingId ? `customrecord_wal_feed_submission #${trackingId} (TEST-MULTI-${feedId})` : 'FAILED to create -- see execution log'}\n\n`
                    + `Submitted feed JSON:\n${feedJson}`;
            } catch (e) {
                resultText = `Error: ${e.message}\n\ncorrelationId: ${correlationId}\n\nSee execution log for full request/response details.`;
                log.error({ title: `Multi-item test upload failed (correlationId=${correlationId})`, details: e });
            }

            context.response.writePage(buildForm({ lookups: rawLookups, resultText }));
        };

        return { onRequest };
    }
);
